title: [Rakesh JV]
logo: /PICS/img.jpeg
description: Welcome to my portfolio! It showcases the skills and experiences that have brought me to where I am today. Hope you enjoy it :)
show_downloads: false
theme: jekyll-theme-cayman
