title: Rakesh JV
logo: /PICS/img.jpeg
description: Hi, this is Rakesh Jeyachandran Vinotha. Welcome to my portfolio! It showcases the skills and experiences that have brought me to where I am today. Hope you like it :)
show_downloads: false
theme: jekyll-theme-cayman
